#!/usr/bin/env bash

set -e

conf_path="${PWD}/.githooks/conf.sh"
source "${conf_path}"

# ビルドの再現性のためイメージはバージョンタグで固定する（更新時はタグを上げる）
docker run -v .:/src --rm --user $(id -u):$(id -g) hugomods/hugo:exts-0.154.5 --gc --minify build
rsync -av --delete -e ssh ${BUILD_DIR} "${USER}@${IP}:${REMOTE_TMP_DIR}"
ssh "${USER}@${IP}" "sudo rm -rf ${REMOTE_BLOG_DIR}"
ssh "${USER}@${IP}" "sudo mv ${REMOTE_TMP_DIR} ${REMOTE_DOCUMENT_ROOT_DIR}"
rm -r ${BUILD_DIR}
